###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsIm5hbWUiOiJhc2RhcnNhaWQiLCJlbWFpbCI6ImFzZGFyc2FpZCIsImlhdCI6MTY1NjEyMjM3MywiZXhwIjoxNjU2MjA4NzczfQ.IPdUTyYzAJdzQwQ8DlX51lbz4nLhCNn6hOTX9pZ3bw0
###
POST http://localhost:5000/login
Content-Type: application/json

{
     "email":"asdarsaid",
     "password":"root"
}


###
POST http://localhost:5000/users
Content-Type: :application/json

{
     "name":"asdar",
     "email":"asdar",
     "password":"password",
     "confirmpassword":"password"
}